language: node_js
node_js:
  - 7.2.1

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

cache:
  directories:
    - node_modules

after_script:
    - npm run coveralls

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
    - master

jobs:
  include:
    - stage: "NPM publish"
      script: echo "Deploying to NPM ..."
      deploy:
        provider: npm
        email: "simonguo.2009@gmail.com"
        api_key: $NPM_API_KEY
        on:
          tags: true
