language: node_js
node_js:
  - 7.2.1

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

cache:
  directories:
    - node_modules

after_script:
    - npm run coveralls

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
    - master

deploy:
  provider: npm
  skip-cleanup: true
  email: "simonguo.2009@gmail.com"
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
